# -*- coding: utf-8 -*-
"""Escape Character

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10Hz5SpiociiKGXwDr-D_5gI5iRIdPsoX
"""

print ('Dia berkata : "Pergilah!"')

print ("Aku menimpali: \"Apakah kau ingin aku 'angkat kaki'?!\"")

print ("\\(^_^)/ (\\-_-/) ")