# -*- coding: utf-8 -*-
"""Manipulasi String 3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1C-5vz8l50i_pw5h0fiAaEA6gQzth1Bwc
"""

template = 'Halo, saya %s dari %s'

print(template % ('Lendis Fabri', 'Indonesia'))

"""Fungsi Format"""

template_nama_asal = 'Halo, saya {nama} dari {asal}'
template_makan_minum = 'Saya suka makan{} dan minum {}'

print (template_nama_asal.format (nama='Putri',asal='Lampung'))
print (template_makan_minum.format ('nasi goreng','air putih'))

"""String Interpolation"""

nama = 'Putri'
asal= 'Indonesia'

print (f' Perkenalkan saya {nama} dari {asal}😎')

"""Memecah String Menjadi List dan Sebaliknya"""

alamat = 'Surabaya, Jawa Timur, Indonesia'

print (alamat.split())
print (alamat.split(','))
print (alamat.split(', '))

print ('❤️'.join (['aku','suka','python']))
print ('😎'.join (alamat.split(', ')))

"""Mengubah sebuah string menjadi upper"""

print ('halo selamat pagi!'.upper ())
print ('Halo Selamat Siang!'.upper())

"""Mengubah String Menjadi Lower"""

print ('APA KABAR?'.lower())
print ('lagi Dimana?'.lower())

"""Titel Case"""

print ('daun tidak pernah membenci angin'. title())
print ('LASKAR PELANGI'.title())

"""reverse case"""

print ('Indonesia Adalah Negara Kepulauan'.swapcase())
print('aKu cInTa NeGeRiKu'.swapcase())

"""Mencari Sebuah Kata"""

angka= '12345'

print('index angka 3:', angka.find('3'))
print('index angka 45:',angka.find('45'))
print('index angka 35:', angka.find('35'))

"""mereplace kata pada string"""

ibu_kota = 'Jakarta'

print(ibu_kota.replace('a', 'i'))
print(ibu_kota.replace('kar', '😎'))
print(ibu_kota.replace('a', ''))

"""menghitung jumlah karakter"""

paragraf= 'Baru-baru ini telah ditemukan sebuah meteor disuatu sungai'
x= paragraf.count('di')

print(f'kata "di" muncul sebanyak {x} kali')