# -*- coding: utf-8 -*-
"""Manipulasi String 2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bYb6SQQynQkztTLyrceFacMSzJCoJ43a

Operasi in pada string
"""

berita = 'Ramai-ramai developer di seluruh dunia mulai menggunakan teks editor masa kini seperti Visual Studio Code, atom, sublime text, dan lain sebagainya.'

print('sublime text' in berita)
print ('notepad++' in berita)

"""Memotong String"""

nama = 'Dhyan Putri'

print (nama[4])
print (nama[7])
print (nama[-1])
print (nama[-3])

"""Slicing String"""

judul= 'Pelajaran Matematika Untuk SD'

print(judul[0:5])
print(judul[:10])
print(judul[10:15])
print(judul[-1:-3])
print(judul[:-3])
print(judul[-5:])

"""Menghitung Panjang String"""

print(len('Indonesia'))
print(len('Malaysia'))

"""Memeriksa Karakter Awal String"""

nomor_telepon_1= '08628653726324'
nomor_telepon_2= '62382738176325'
nomor_telepon_3= '+6289338927438'

kode_negara= '+62'
print(nomor_telepon_1.startswith(kode_negara))
print(nomor_telepon_2.startswith(kode_negara))
print(nomor_telepon_3.startswith(kode_negara))

"""Memeriksa Karakter Akhir String"""

email_1= 'presiden@gmail.com'
email_2= 'predisen@outlook.com'

print(email_1.endswith('gmail.com'))
print(email_2.endswith('gamil.com'))