# -*- coding: utf-8 -*-
"""Manipulasi String

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15ebfeghVPxZatGDH1tZs1mo3pyOSmvQ3
"""

asal_kota= "Bandar Lampung"
kode_pos= 35144

asal_kota_kode_pos= asal_kota + str(kode_pos)

print(asal_kota_kode_pos)

nama =